version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    tty: true
    networks:
      - node-network
    depends_on:
      - db
  db:
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
